name: NeoUNet.Demo

val_on_test: false
from_segment_model: null

trainer:
  resume_from_checkpoint: null
  max_epochs: 2
  gpus: 0
  auto_select_gpus: false
  overfit_batches: 10

dataset:
  cls: polypnet.data.cvc.CvcDataset
  kwargs:
    root_dir: data/CVC-ClinicDB

val_dataset:
  split_from_train: true
  split_ratio: 0.2
  cls: polypnet.data.cvc.CvcDataset

loader:
  batch_size: 2
  num_workers: 2

test_datasets:
- cls: polypnet.data.cvc.CvcDataset
  kwargs:
    root_dir: data/CVC-ClinicDB
  name: default

test_loader:
  num_workers: 2

model:
  cls: polypnet.model.neounet.NeoUNet
  kwargs: {}

wrapper:
  kwargs:
    test_input_size:
    - 352
    - 352
    train_sizes:
    - - 256
      - 256
    - - 352
      - 352
    - - 448
      - 448

optimizer:
  cls: torch.optim.SGD
  kwargs:
    lr: 0.001
    momentum: 0.9
    nesterov: true

scheduler:
  cls: polypnet.optim.warmup_cos.CosineAnnealingWarmupLR
  kwargs:
    T_max: 195
    warmup_epochs: 5

callbacks:
  early_stop:
    patience: 30
  result_sample:
    images_per_epoch: 5
    skip_first: 5

augment:
  kwargs:
    prob: 0.7

loss:
  kwargs: {}
  losses:
  - cls: polypnet.losses.proba.BinaryCrossEntropyLoss
    kwargs: {}
  - cls: polypnet.losses.region.TverskyLoss
    kwargs:
      alpha: 0.3
