name: MSEG.Eso.1
with_mlflow: false
val_on_test: true

from_segment_model: null

trainer:
  resume_from_checkpoint: null
  max_epochs: 71
  gpus: 1
  auto_select_gpus: true

dataset:
  cls: polypnet.data.upper.UpperPolypDataset
  kwargs:
    root_dir: data/stomach/train
    image_dir: images
    mask_dir: masks

val_dataset:
  split_from_train: true
  split_ratio: 0.15
  split_seed: 66

loader:
  batch_size: 12
  num_workers: 16

test_datasets:
- cls: polypnet.data.upper.UpperPolypDataset
  kwargs:
    root_dir: data/stomach/test
    image_dir: images
    mask_dir: masks
  name: default
- cls: polypnet.data.upper.UpperPolypDataset
  kwargs:
    root_dir: data/stomach/train
    image_dir: images
    mask_dir: masks
  name: train

test_loader:
  num_workers: 2

model:
  cls: polypnet.model.mseg.HarDMSEG
  kwargs: {}

wrapper:
  kwargs:
    test_input_size:
    - 352
    - 352
    train_sizes:
    - - 256
      - 256
    - - 352
      - 352
    - - 448
      - 448

agc:
  enabled: false
  kwargs:
    clipping: 0.05

optimizer:
  cls: torch.optim.SGD
  kwargs:
    lr: 0.001
    momentum: 0.9
    nesterov: true

scheduler:
  cls: polypnet.optim.warmup_cos.CosineAnnealingWarmupLR
  kwargs:
    T_max: 66
    warmup_epochs: 5

callbacks:
  early_stop:
    patience: 20
  result_sample:
    images_per_epoch: 20
    skip_first: 5

augment:
  kwargs:
    prob: 0.7

loss:
  kwargs: {}
  losses:
  - cls: polypnet.losses.proba.BinaryCrossEntropyLoss
    kwargs: {}
  - cls: polypnet.losses.region.TverskyLoss
    kwargs:
      alpha: 0.3
